import Foundation

struct PersonalizedLine: Identifiable, Hashable, Codable {
    let id: String
    let title: String
    let contentType: String // "health" or "advocacy"
    let line: String
    let riskGroups: [String]
    let conditionTags: [String]
    let complicationTags: [String]
    let topicTags: [String]
    let stage: [String]
    let priority: Int
}

enum PersonalizedLineSeedData {
    static let lines: [PersonalizedLine] = [
        PersonalizedLine(
            id: "advocate-biggest-health-advocate",
            title: "Biggest Health Advocate",
            contentType: "advocacy",
            line: "You are your biggest health advocate, and your voice can help change “what is” into “what should be.” If something feels off, it is okay to speak up more than once.",
            riskGroups: ["general"],
            conditionTags: [],
            complicationTags: [],
            topicTags: ["advocacy", "support"],
            stage: ["pregnancy", "postpartum", "lifetime"],
            priority: 1
        ),
        PersonalizedLine(
            id: "advocate-clear-plan",
            title: "Ask for a Clear Plan",
            contentType: "advocacy",
            line: "Before you leave a visit, ask what you should watch for, who you should call, and when you should follow up. A clear plan can make care feel less confusing.",
            riskGroups: ["general", "pregnancy", "postpartum"],
            conditionTags: [],
            complicationTags: [],
            topicTags: ["advocacy", "care_team", "support"],
            stage: ["pregnancy", "postpartum"],
            priority: 1
        ),
        PersonalizedLine(
            id: "urgent-severe-symptoms",
            title: "Severe Symptoms Matter",
            contentType: "health",
            line: "Severe chest pain, trouble breathing, fainting, one-sided weakness, or a severe headache that will not go away should be treated as urgent. Tell care teams that you are pregnant or were pregnant within the last year.",
            riskGroups: ["general", "pregnancy", "postpartum", "elevated_heart_risk"],
            conditionTags: [],
            complicationTags: [],
            topicTags: ["urgent_symptoms", "symptoms", "heart_health"],
            stage: ["pregnancy", "postpartum"],
            priority: 1
        ),
        PersonalizedLine(
            id: "general-new-different",
            title: "New or Different Counts",
            contentType: "health",
            line: "Pregnancy can bring many body changes, but new, sudden, or worsening symptoms deserve attention. You know your baseline better than anyone else.",
            riskGroups: ["general", "pregnancy"],
            conditionTags: [],
            complicationTags: [],
            topicTags: ["general_pregnancy", "symptoms", "advocacy"],
            stage: ["pregnancy"],
            priority: 3
        ),
        PersonalizedLine(
            id: "postpartum-still-counts",
            title: "Postpartum Still Counts",
            contentType: "health",
            line: "Symptoms after delivery still matter, even weeks or months later. When seeking care, say clearly that you recently gave birth or are postpartum.",
            riskGroups: ["general", "postpartum"],
            conditionTags: [],
            complicationTags: [],
            topicTags: ["postpartum", "symptoms", "advocacy"],
            stage: ["postpartum"],
            priority: 2
        ),
        PersonalizedLine(
            id: "track-symptoms",
            title: "Track the Pattern",
            contentType: "advocacy",
            line: "Write down when a symptom started, what makes it better or worse, and whether it is changing. A simple note can make your next conversation with a clinician more useful.",
            riskGroups: ["general"],
            conditionTags: [],
            complicationTags: [],
            topicTags: ["symptoms", "advocacy", "care_team"],
            stage: ["pregnancy", "postpartum"],
            priority: 4
        ),
        PersonalizedLine(
            id: "daily-body-checkin",
            title: "Daily Body Check-In",
            contentType: "health",
            line: "A quick daily check-in with breathing, swelling, headaches, mood, and movement can help you notice changes early. Awareness is not panic; it is preparation.",
            riskGroups: ["general", "pregnancy"],
            conditionTags: [],
            complicationTags: [],
            topicTags: ["general_pregnancy", "symptoms", "mental_health"],
            stage: ["pregnancy"],
            priority: 4
        ),
        PersonalizedLine(
            id: "heart-condition-care-team",
            title: "Heart Condition Care Team",
            contentType: "advocacy",
            line: "If you were born with a heart condition or have a heart problem, ask whether cardiology should be part of your plan. Coordinated care can make symptoms and medication questions easier to manage.",
            riskGroups: ["known_heart_condition", "elevated_heart_risk", "higher_support_needs"],
            conditionTags: ["congenital_heart_disease", "heart_disease"],
            complicationTags: [],
            topicTags: ["heart_health", "care_team", "medication_safety", "advocacy"],
            stage: ["pregnancy", "postpartum"],
            priority: 1
        ),
        PersonalizedLine(
            id: "heart-symptoms-personal",
            title: "Heart Symptoms Are Personal",
            contentType: "health",
            line: "For someone with a heart history, new chest pressure, fainting, fast heartbeat, unusual swelling, or shortness of breath may be especially important to discuss quickly. Ask which symptoms should trigger urgent care.",
            riskGroups: ["known_heart_condition", "elevated_heart_risk"],
            conditionTags: ["heart_disease", "congenital_heart_disease"],
            complicationTags: [],
            topicTags: ["heart_health", "symptoms", "urgent_symptoms"],
            stage: ["pregnancy", "postpartum"],
            priority: 1
        ),
        PersonalizedLine(
            id: "heart-meds-review",
            title: "Medication Review",
            contentType: "advocacy",
            line: "Do not stop or restart heart medicines without medical guidance. Ask your clinician to review what is safe during pregnancy, breastfeeding, and postpartum recovery.",
            riskGroups: ["known_heart_condition", "elevated_heart_risk"],
            conditionTags: ["heart_disease", "congenital_heart_disease"],
            complicationTags: [],
            topicTags: ["medication_safety", "heart_health", "care_team"],
            stage: ["pregnancy", "postpartum"],
            priority: 2
        ),
        PersonalizedLine(
            id: "heart-birth-plan",
            title: "Heart-Aware Birth Plan",
            contentType: "advocacy",
            line: "A heart-aware plan should include who to call, what symptoms matter, and what follow-up is needed after delivery. Ask for the plan in writing so everyone is working from the same information.",
            riskGroups: ["known_heart_condition", "elevated_heart_risk"],
            conditionTags: ["heart_disease", "congenital_heart_disease"],
            complicationTags: [],
            topicTags: ["heart_health", "care_team", "advocacy"],
            stage: ["pregnancy", "postpartum"],
            priority: 2
        ),
        PersonalizedLine(
            id: "elevated-risk-not-fear",
            title: "Risk-Aware, Not Fear-Based",
            contentType: "health",
            line: "Elevated heart attention does not mean something bad will happen. It means your app should surface more relevant questions, symptoms, and follow-up reminders.",
            riskGroups: ["elevated_heart_risk"],
            conditionTags: [],
            complicationTags: [],
            topicTags: ["heart_health", "screening", "advocacy"],
            stage: ["pregnancy", "postpartum", "lifetime"],
            priority: 3
        ),
        PersonalizedLine(
            id: "bp-know-numbers",
            title: "Know Your BP Numbers",
            contentType: "advocacy",
            line: "If you have high blood pressure or a blood-pressure complication, ask what numbers should make you call. Knowing the threshold ahead of time can reduce guesswork.",
            riskGroups: ["blood_pressure", "elevated_heart_risk"],
            conditionTags: ["high_blood_pressure"],
            complicationTags: ["preeclampsia", "gestational_hypertension"],
            topicTags: ["blood_pressure", "screening", "advocacy"],
            stage: ["pregnancy", "postpartum"],
            priority: 1
        ),
        PersonalizedLine(
            id: "bp-headache-vision",
            title: "Headache + Vision Changes",
            contentType: "health",
            line: "A severe headache, vision changes, chest pain, or sudden swelling can be important warning signs for people with blood pressure risk. Do not wait on severe or worsening symptoms.",
            riskGroups: ["blood_pressure", "elevated_heart_risk"],
            conditionTags: ["high_blood_pressure"],
            complicationTags: ["preeclampsia", "gestational_hypertension"],
            topicTags: ["blood_pressure", "symptoms", "urgent_symptoms"],
            stage: ["pregnancy", "postpartum"],
            priority: 1
        ),
        PersonalizedLine(
            id: "bp-postpartum-followup",
            title: "Postpartum BP Follow-Up",
            contentType: "advocacy",
            line: "Blood pressure concerns can continue or appear after delivery. Ask when your blood pressure should be checked and who manages follow-up after your postpartum visit.",
            riskGroups: ["blood_pressure", "postpartum", "elevated_heart_risk"],
            conditionTags: ["high_blood_pressure"],
            complicationTags: ["preeclampsia", "gestational_hypertension"],
            topicTags: ["blood_pressure", "postpartum", "screening", "care_team"],
            stage: ["postpartum"],
            priority: 1
        ),
        PersonalizedLine(
            id: "home-bp-cuff",
            title: "Home Cuff Confidence",
            contentType: "advocacy",
            line: "If you are asked to check blood pressure at home, ask your care team to confirm cuff size, timing, and what to do with the results. Good instructions make home monitoring more useful.",
            riskGroups: ["blood_pressure"],
            conditionTags: ["high_blood_pressure"],
            complicationTags: ["preeclampsia", "gestational_hypertension"],
            topicTags: ["blood_pressure", "screening", "care_team"],
            stage: ["pregnancy", "postpartum"],
            priority: 3
        ),
        PersonalizedLine(
            id: "gestational-hypertension-plan",
            title: "Gestational Hypertension Plan",
            contentType: "health",
            line: "Gestational hypertension deserves a clear follow-up plan because it can overlap with preeclampsia symptoms. Ask what changes would require a call, visit, or urgent evaluation.",
            riskGroups: ["blood_pressure", "elevated_heart_risk"],
            conditionTags: [],
            complicationTags: ["gestational_hypertension"],
            topicTags: ["blood_pressure", "symptoms", "care_team"],
            stage: ["pregnancy", "postpartum"],
            priority: 2
        ),
        PersonalizedLine(
            id: "preeclampsia-speak-up",
            title: "Preeclampsia Speak-Up Line",
            contentType: "advocacy",
            line: "If you have preeclampsia, tell clinicians directly when symptoms are new, severe, or getting worse. You are allowed to say, “I am worried this could be related to my blood pressure.”",
            riskGroups: ["blood_pressure", "elevated_heart_risk", "higher_support_needs"],
            conditionTags: ["high_blood_pressure"],
            complicationTags: ["preeclampsia"],
            topicTags: ["blood_pressure", "urgent_symptoms", "advocacy", "symptoms"],
            stage: ["pregnancy", "postpartum"],
            priority: 1
        ),
        PersonalizedLine(
            id: "diabetes-followup",
            title: "Diabetes Follow-Up",
            contentType: "advocacy",
            line: "Diabetes or gestational diabetes can make follow-up screening more relevant after pregnancy. Ask who will check your blood sugar and how often after postpartum care ends.",
            riskGroups: ["metabolic", "elevated_heart_risk"],
            conditionTags: ["diabetes"],
            complicationTags: ["gestational_diabetes"],
            topicTags: ["diabetes", "screening", "care_team", "heart_health"],
            stage: ["pregnancy", "postpartum", "lifetime"],
            priority: 2
        ),
        PersonalizedLine(
            id: "gdm-long-term",
            title: "Gestational Diabetes History",
            contentType: "health",
            line: "A gestational diabetes history is useful information for future primary care, not something to forget after delivery. Keep it on your health history list.",
            riskGroups: ["metabolic", "elevated_heart_risk", "postpartum"],
            conditionTags: [],
            complicationTags: ["gestational_diabetes"],
            topicTags: ["diabetes", "postpartum", "screening", "heart_health"],
            stage: ["postpartum", "lifetime"],
            priority: 2
        ),
        PersonalizedLine(
            id: "nutrition-blood-sugar",
            title: "Nutrition Support",
            contentType: "advocacy",
            line: "Food advice should be realistic, culturally respectful, and matched to your life. Ask for nutrition support that works with your budget, schedule, and preferences.",
            riskGroups: ["metabolic", "higher_support_needs"],
            conditionTags: ["diabetes"],
            complicationTags: ["gestational_diabetes"],
            topicTags: ["nutrition", "diabetes", "support", "advocacy"],
            stage: ["pregnancy", "postpartum"],
            priority: 4
        ),
        PersonalizedLine(
            id: "diabetes-bp-connection",
            title: "Blood Sugar + BP",
            contentType: "health",
            line: "Blood sugar history and blood pressure history can both matter for long-term heart health. Ask whether you need primary care follow-up beyond the routine postpartum visit.",
            riskGroups: ["metabolic", "blood_pressure", "elevated_heart_risk"],
            conditionTags: ["diabetes", "high_blood_pressure"],
            complicationTags: ["gestational_diabetes", "preeclampsia", "gestational_hypertension"],
            topicTags: ["diabetes", "blood_pressure", "heart_health", "screening"],
            stage: ["postpartum", "lifetime"],
            priority: 2
        ),
        PersonalizedLine(
            id: "metabolic-small-steps",
            title: "Small Steps Count",
            contentType: "health",
            line: "Metabolic health support should not feel all-or-nothing. Small follow-up steps, like screening, medication review, and realistic nutrition goals, can still be meaningful.",
            riskGroups: ["metabolic"],
            conditionTags: ["diabetes"],
            complicationTags: ["gestational_diabetes"],
            topicTags: ["diabetes", "nutrition", "screening", "support"],
            stage: ["pregnancy", "postpartum", "lifetime"],
            priority: 5
        ),
        PersonalizedLine(
            id: "breathing-urgent",
            title: "Breathing Should Be Taken Seriously",
            contentType: "health",
            line: "Trouble breathing, chest pain, blue lips, fainting, or breathlessness that suddenly worsens should be treated as urgent. Breathing symptoms deserve clear attention in pregnancy and postpartum.",
            riskGroups: ["lung_condition", "elevated_heart_risk"],
            conditionTags: ["lung_disease", "breathing_problem"],
            complicationTags: [],
            topicTags: ["breathing", "urgent_symptoms", "symptoms", "heart_health"],
            stage: ["pregnancy", "postpartum"],
            priority: 1
        ),
        PersonalizedLine(
            id: "lung-condition-plan",
            title: "Breathing Plan",
            contentType: "advocacy",
            line: "If you have lung disease or recurring breathing problems, ask what symptoms are expected and what symptoms should trigger a same-day call. A written plan can help you act quickly.",
            riskGroups: ["lung_condition", "elevated_heart_risk"],
            conditionTags: ["lung_disease", "breathing_problem"],
            complicationTags: [],
            topicTags: ["breathing", "care_team", "advocacy"],
            stage: ["pregnancy", "postpartum"],
            priority: 2
        ),
        PersonalizedLine(
            id: "breathing-not-just-anxiety",
            title: "Not Just Anxiety",
            contentType: "advocacy",
            line: "Anxiety can affect breathing, but new or severe shortness of breath should not be dismissed automatically. It is okay to ask for a medical check when breathing feels different or unsafe.",
            riskGroups: ["lung_condition", "higher_support_needs"],
            conditionTags: ["breathing_problem"],
            complicationTags: [],
            topicTags: ["breathing", "symptoms", "mental_health", "advocacy"],
            stage: ["pregnancy", "postpartum"],
            priority: 3
        ),
        PersonalizedLine(
            id: "lung-meds-check",
            title: "Inhalers and Medicines",
            contentType: "advocacy",
            line: "If you use inhalers or breathing medicines, ask whether anything should change during pregnancy or postpartum. Medication safety questions are valid and important.",
            riskGroups: ["lung_condition"],
            conditionTags: ["lung_disease", "breathing_problem"],
            complicationTags: [],
            topicTags: ["breathing", "medication_safety", "care_team"],
            stage: ["pregnancy", "postpartum"],
            priority: 4
        ),
        PersonalizedLine(
            id: "substance-nonjudgment",
            title: "Nonjudgmental Support",
            contentType: "advocacy",
            line: "You deserve care that focuses on safety, support, and honesty, not shame. If substances or medication misuse are part of your story, ask for help in a nonjudgmental way.",
            riskGroups: ["substance_use", "higher_support_needs"],
            conditionTags: ["substance_use"],
            complicationTags: [],
            topicTags: ["support", "advocacy", "care_team", "medication_safety"],
            stage: ["pregnancy", "postpartum"],
            priority: 2
        ),
        PersonalizedLine(
            id: "substance-med-safety",
            title: "Medication and Substance Safety",
            contentType: "health",
            line: "Some medicines, alcohol, and substances can interact or affect pregnancy and postpartum recovery. Ask your care team what is safest for you before changing anything alone.",
            riskGroups: ["substance_use", "higher_support_needs"],
            conditionTags: ["substance_use", "alcohol_use_history"],
            complicationTags: [],
            topicTags: ["medication_safety", "support", "care_team"],
            stage: ["pregnancy", "postpartum"],
            priority: 2
        ),
        PersonalizedLine(
            id: "alcohol-history-support",
            title: "Alcohol History Support",
            contentType: "advocacy",
            line: "A history of alcohol-related treatment or hospitalization is health information that can help your care team support you. You can ask for resources without needing to explain everything at once.",
            riskGroups: ["substance_use", "higher_support_needs"],
            conditionTags: ["alcohol_use_history"],
            complicationTags: [],
            topicTags: ["support", "mental_health", "advocacy", "care_team"],
            stage: ["pregnancy", "postpartum"],
            priority: 3
        ),
        PersonalizedLine(
            id: "support-relapse-plan",
            title: "Support Plan",
            contentType: "advocacy",
            line: "If recovery or substance safety is part of your care, ask for a plan for stress, cravings, emergencies, and postpartum support. Planning ahead is a strength.",
            riskGroups: ["substance_use", "higher_support_needs"],
            conditionTags: ["substance_use", "alcohol_use_history"],
            complicationTags: [],
            topicTags: ["support", "mental_health", "care_team"],
            stage: ["pregnancy", "postpartum"],
            priority: 3
        ),
        PersonalizedLine(
            id: "mental-health-urgent",
            title: "Mental Health Is Health",
            contentType: "health",
            line: "Thoughts of harming yourself or your baby deserve immediate support and care. You are not a burden for asking for urgent help.",
            riskGroups: ["general", "higher_support_needs", "postpartum"],
            conditionTags: [],
            complicationTags: [],
            topicTags: ["mental_health", "urgent_symptoms", "support"],
            stage: ["pregnancy", "postpartum"],
            priority: 1
        ),
        PersonalizedLine(
            id: "digestive-history-care",
            title: "Digestive History Matters",
            contentType: "health",
            line: "Digestive surgery or chronic digestive conditions can affect nutrition, hydration, and medication questions. Make sure this history is visible to your pregnancy or postpartum care team.",
            riskGroups: ["digestive_condition", "higher_support_needs", "preexisting_condition"],
            conditionTags: ["digestive_condition"],
            complicationTags: [],
            topicTags: ["nutrition", "medication_safety", "care_team"],
            stage: ["pregnancy", "postpartum"],
            priority: 3
        ),
        PersonalizedLine(
            id: "digestive-med-absorption",
            title: "Medication Absorption Question",
            contentType: "advocacy",
            line: "If you have had stomach or intestinal surgery, ask whether any medicines or vitamins need special timing, form, or monitoring. This is a practical safety question, not a small detail.",
            riskGroups: ["digestive_condition"],
            conditionTags: ["digestive_condition"],
            complicationTags: [],
            topicTags: ["medication_safety", "nutrition", "care_team", "advocacy"],
            stage: ["pregnancy", "postpartum"],
            priority: 4
        ),
        PersonalizedLine(
            id: "nausea-not-normal",
            title: "Severe Nausea Check",
            contentType: "health",
            line: "Severe nausea or vomiting that prevents fluids, food, or medicines from staying down is worth discussing promptly. Hydration and nutrition support matter for you, too.",
            riskGroups: ["digestive_condition", "pregnancy"],
            conditionTags: ["digestive_condition"],
            complicationTags: [],
            topicTags: ["nutrition", "symptoms", "care_team"],
            stage: ["pregnancy"],
            priority: 3
        ),
        PersonalizedLine(
            id: "nutrition-personalized",
            title: "Personalized Nutrition",
            contentType: "advocacy",
            line: "Nutrition advice should fit your medical history, culture, symptoms, and access to food. Ask for options that work in your real life.",
            riskGroups: ["general", "digestive_condition", "metabolic"],
            conditionTags: ["digestive_condition", "diabetes"],
            complicationTags: ["gestational_diabetes", "anemia"],
            topicTags: ["nutrition", "support", "advocacy"],
            stage: ["pregnancy", "postpartum"],
            priority: 5
        ),
        PersonalizedLine(
            id: "preexisting-history-list",
            title: "Keep a Health History List",
            contentType: "advocacy",
            line: "Preexisting conditions can shape pregnancy and postpartum follow-up. Keep a short list of diagnoses, medicines, surgeries, and specialists so each visit starts with the full picture.",
            riskGroups: ["preexisting_condition", "higher_support_needs"],
            conditionTags: [],
            complicationTags: [],
            topicTags: ["care_team", "screening", "advocacy"],
            stage: ["pregnancy", "postpartum"],
            priority: 3
        ),
        PersonalizedLine(
            id: "higher-support-written-plan",
            title: "Write It Down",
            contentType: "advocacy",
            line: "If you have multiple health needs, ask for the plan in writing: symptoms, medications, follow-up, and who to call. Written plans protect you from having to remember everything under stress.",
            riskGroups: ["higher_support_needs"],
            conditionTags: [],
            complicationTags: [],
            topicTags: ["care_team", "support", "advocacy"],
            stage: ["pregnancy", "postpartum"],
            priority: 2
        ),
        PersonalizedLine(
            id: "multi-tag-care-coordination",
            title: "Care Coordination",
            contentType: "advocacy",
            line: "When several tags apply to you, your feed should mix content from each area instead of focusing on only one condition. Your care plan can also ask who is responsible for each part of follow-up.",
            riskGroups: ["higher_support_needs", "preexisting_condition"],
            conditionTags: [],
            complicationTags: [],
            topicTags: ["care_team", "support", "advocacy"],
            stage: ["pregnancy", "postpartum"],
            priority: 4
        ),
        PersonalizedLine(
            id: "anemia-energy",
            title: "Anemia and Energy",
            contentType: "health",
            line: "Fatigue can be common, but anemia can make tiredness, dizziness, or shortness of breath feel worse. Ask what follow-up, nutrition, or iron plan is right for you.",
            riskGroups: ["higher_support_needs"],
            conditionTags: [],
            complicationTags: ["anemia"],
            topicTags: ["symptoms", "nutrition", "screening", "care_team"],
            stage: ["pregnancy", "postpartum"],
            priority: 3
        ),
        PersonalizedLine(
            id: "anemia-followup",
            title: "Ask About Anemia Follow-Up",
            contentType: "advocacy",
            line: "If you were told you have anemia, ask when labs should be rechecked and what symptoms should prompt a call. A clear plan can make treatment easier to follow.",
            riskGroups: ["higher_support_needs"],
            conditionTags: [],
            complicationTags: ["anemia"],
            topicTags: ["screening", "nutrition", "advocacy"],
            stage: ["pregnancy", "postpartum"],
            priority: 4
        ),
        PersonalizedLine(
            id: "placenta-previa-bleeding",
            title: "Bleeding Risk Plan",
            contentType: "health",
            line: "If placenta previa or bleeding risk is part of your pregnancy, ask exactly what bleeding, pain, or contractions should trigger urgent care. Do not wait on heavy bleeding or severe symptoms.",
            riskGroups: ["higher_support_needs", "pregnancy"],
            conditionTags: [],
            complicationTags: ["placenta_previa", "bleeding_risk"],
            topicTags: ["urgent_symptoms", "symptoms", "care_team"],
            stage: ["pregnancy"],
            priority: 1
        ),
        PersonalizedLine(
            id: "bleeding-speak-up",
            title: "Bleeding Is Worth Reporting",
            contentType: "advocacy",
            line: "Bleeding during pregnancy or after delivery should be reported based on your care team’s instructions, especially if it is heavy, sudden, or paired with dizziness or pain. You are not overreacting by calling.",
            riskGroups: ["higher_support_needs", "pregnancy", "postpartum"],
            conditionTags: [],
            complicationTags: ["bleeding_risk", "placenta_previa"],
            topicTags: ["urgent_symptoms", "symptoms", "advocacy"],
            stage: ["pregnancy", "postpartum"],
            priority: 1
        ),
        PersonalizedLine(
            id: "cholestasis-itching",
            title: "Itching Can Be a Symptom",
            contentType: "health",
            line: "Intense itching, especially if it is new or worsening, is worth discussing with your care team when cholestasis is a concern. Ask what testing and monitoring are recommended for your situation.",
            riskGroups: ["higher_support_needs"],
            conditionTags: [],
            complicationTags: ["cholestasis"],
            topicTags: ["symptoms", "screening", "care_team"],
            stage: ["pregnancy"],
            priority: 2
        ),
        PersonalizedLine(
            id: "cholestasis-questions",
            title: "Cholestasis Questions",
            contentType: "advocacy",
            line: "If cholestasis is on your chart, ask what symptoms to watch for, when labs are repeated, and how the pregnancy plan might change. Specific questions help turn uncertainty into next steps.",
            riskGroups: ["higher_support_needs"],
            conditionTags: [],
            complicationTags: ["cholestasis"],
            topicTags: ["advocacy", "care_team", "screening"],
            stage: ["pregnancy"],
            priority: 3
        ),
        PersonalizedLine(
            id: "postpartum-visit-prep",
            title: "Postpartum Visit Prep",
            contentType: "advocacy",
            line: "Postpartum care is not just a quick recovery check. Bring questions about bleeding, mood, blood pressure, diabetes screening, medications, pain, sleep, and support.",
            riskGroups: ["postpartum", "general"],
            conditionTags: [],
            complicationTags: [],
            topicTags: ["postpartum", "advocacy", "care_team", "screening"],
            stage: ["postpartum"],
            priority: 3
        ),
        PersonalizedLine(
            id: "postpartum-mood",
            title: "Mood Changes Deserve Care",
            contentType: "health",
            line: "If sadness, anxiety, panic, anger, or scary thoughts feel intense or persistent, tell someone and ask for care. Mental health is part of postpartum health.",
            riskGroups: ["postpartum", "higher_support_needs"],
            conditionTags: [],
            complicationTags: [],
            topicTags: ["postpartum", "mental_health", "support", "symptoms"],
            stage: ["postpartum"],
            priority: 2
        ),
        PersonalizedLine(
            id: "postpartum-primary-care",
            title: "Beyond Six Weeks",
            contentType: "advocacy",
            line: "Some pregnancy conditions matter long after the postpartum visit. Ask whether primary care, cardiology, or another clinician should continue follow-up.",
            riskGroups: ["postpartum", "elevated_heart_risk", "preexisting_condition"],
            conditionTags: [],
            complicationTags: ["preeclampsia", "gestational_diabetes", "gestational_hypertension"],
            topicTags: ["postpartum", "screening", "heart_health", "care_team"],
            stage: ["postpartum", "lifetime"],
            priority: 2
        ),
        PersonalizedLine(
            id: "screening-prevention",
            title: "Screening Is Prevention",
            contentType: "health",
            line: "Screening is not about blaming you; it is about catching patterns early. Ask which checks make sense based on your pregnancy history and health conditions.",
            riskGroups: ["general", "elevated_heart_risk", "preexisting_condition"],
            conditionTags: [],
            complicationTags: [],
            topicTags: ["screening", "advocacy", "heart_health"],
            stage: ["pregnancy", "postpartum", "lifetime"],
            priority: 4
        ),
        PersonalizedLine(
            id: "care-team-roles",
            title: "Who Owns Follow-Up?",
            contentType: "advocacy",
            line: "When several clinicians are involved, ask who owns each part of the plan. Knowing whether OB, primary care, cardiology, or another specialist is responsible can prevent gaps.",
            riskGroups: ["general", "higher_support_needs"],
            conditionTags: [],
            complicationTags: [],
            topicTags: ["care_team", "advocacy", "support"],
            stage: ["pregnancy", "postpartum"],
            priority: 3
        ),
        PersonalizedLine(
            id: "med-safety-universal",
            title: "Medication Questions Are Valid",
            contentType: "advocacy",
            line: "Medication safety can change during pregnancy, breastfeeding, and postpartum recovery. Ask before stopping, starting, or mixing medicines or supplements.",
            riskGroups: ["general", "preexisting_condition"],
            conditionTags: [],
            complicationTags: [],
            topicTags: ["medication_safety", "care_team", "advocacy"],
            stage: ["pregnancy", "postpartum"],
            priority: 3
        ),
        PersonalizedLine(
            id: "symptom-language",
            title: "Use Specific Words",
            contentType: "advocacy",
            line: "Instead of saying “I feel weird,” try describing the exact symptom, severity, timing, and what changed. Specific words can make it easier for clinicians to triage your concern.",
            riskGroups: ["general"],
            conditionTags: [],
            complicationTags: [],
            topicTags: ["symptoms", "advocacy", "care_team"],
            stage: ["pregnancy", "postpartum"],
            priority: 4
        ),
        PersonalizedLine(
            id: "urgent-not-routine",
            title: "Urgent Is Not Routine",
            contentType: "advocacy",
            line: "If a symptom feels severe, sudden, or concerning, it may not belong in a routine message queue. Ask where you should go for same-day or emergency help.",
            riskGroups: ["general", "higher_support_needs"],
            conditionTags: [],
            complicationTags: [],
            topicTags: ["urgent_symptoms", "advocacy", "care_team"],
            stage: ["pregnancy", "postpartum"],
            priority: 1
        ),
        PersonalizedLine(
            id: "bp-diabetes-combo",
            title: "BP + Diabetes Combo",
            contentType: "health",
            line: "When blood pressure and blood sugar both matter, follow-up should not be siloed. Ask how these histories affect your future heart-health screening plan.",
            riskGroups: ["blood_pressure", "metabolic", "elevated_heart_risk"],
            conditionTags: ["high_blood_pressure", "diabetes"],
            complicationTags: ["gestational_hypertension", "gestational_diabetes", "preeclampsia"],
            topicTags: ["blood_pressure", "diabetes", "heart_health", "screening"],
            stage: ["postpartum", "lifetime"],
            priority: 2
        ),
        PersonalizedLine(
            id: "heart-lung-combo",
            title: "Heart + Breathing Combo",
            contentType: "health",
            line: "If you have both heart and breathing concerns, new shortness of breath deserves careful attention. Ask your care team how to tell expected changes from symptoms that need urgent care.",
            riskGroups: ["known_heart_condition", "lung_condition", "elevated_heart_risk"],
            conditionTags: ["heart_disease", "lung_disease", "breathing_problem"],
            complicationTags: [],
            topicTags: ["heart_health", "breathing", "urgent_symptoms", "care_team"],
            stage: ["pregnancy", "postpartum"],
            priority: 1
        ),
        PersonalizedLine(
            id: "preexisting-meds-combo",
            title: "Condition + Medication Combo",
            contentType: "advocacy",
            line: "If you entered pregnancy with a chronic condition, medication review should be part of care, not an afterthought. Ask what should continue, change, or be monitored.",
            riskGroups: ["preexisting_condition", "higher_support_needs"],
            conditionTags: ["heart_disease", "diabetes", "lung_disease", "digestive_condition"],
            complicationTags: [],
            topicTags: ["medication_safety", "care_team", "screening"],
            stage: ["pregnancy", "postpartum"],
            priority: 3
        ),
        PersonalizedLine(
            id: "higher-support-advocacy",
            title: "Higher Support, Stronger Voice",
            contentType: "advocacy",
            line: "Needing more support does not make you difficult. It means your app and care team should give you clearer questions, safer reminders, and more specific follow-up.",
            riskGroups: ["higher_support_needs"],
            conditionTags: [],
            complicationTags: [],
            topicTags: ["advocacy", "support", "care_team"],
            stage: ["pregnancy", "postpartum"],
            priority: 2
        ),
        PersonalizedLine(
            id: "support-is-care",
            title: "Support Is Care",
            contentType: "advocacy",
            line: "Asking for support with transportation, appointments, food, mood, recovery, or safety is part of health care. Your needs outside the exam room can affect your health, too.",
            riskGroups: ["general", "higher_support_needs"],
            conditionTags: [],
            complicationTags: [],
            topicTags: ["support", "mental_health", "advocacy"],
            stage: ["pregnancy", "postpartum"],
            priority: 5
        ),
        PersonalizedLine(
            id: "mental-health-ask",
            title: "Ask About Mood Early",
            contentType: "advocacy",
            line: "You do not need to wait until things feel unbearable to ask about mood or anxiety. Early support can make pregnancy and postpartum feel less isolating.",
            riskGroups: ["general", "postpartum"],
            conditionTags: [],
            complicationTags: [],
            topicTags: ["mental_health", "support", "advocacy"],
            stage: ["pregnancy", "postpartum"],
            priority: 4
        ),
        PersonalizedLine(
            id: "movement-question",
            title: "Movement Questions",
            contentType: "health",
            line: "If fetal movement slows or feels very different during pregnancy, contact your care team based on their instructions. You are allowed to ask even if you are unsure.",
            riskGroups: ["pregnancy", "general"],
            conditionTags: [],
            complicationTags: [],
            topicTags: ["general_pregnancy", "symptoms", "advocacy"],
            stage: ["pregnancy"],
            priority: 2
        ),
        PersonalizedLine(
            id: "swelling-context",
            title: "Swelling Context",
            contentType: "health",
            line: "Some swelling can happen in pregnancy, but sudden swelling of the face or hands, especially with headache or vision changes, deserves quick attention. Context matters.",
            riskGroups: ["general", "pregnancy", "blood_pressure"],
            conditionTags: ["high_blood_pressure"],
            complicationTags: ["preeclampsia"],
            topicTags: ["symptoms", "urgent_symptoms", "blood_pressure"],
            stage: ["pregnancy", "postpartum"],
            priority: 1
        ),
        PersonalizedLine(
            id: "fever-check",
            title: "Fever Check",
            contentType: "health",
            line: "A fever during pregnancy or postpartum is worth calling about, especially if you also feel very unwell, have pain, or notice worsening symptoms. Ask where you should be evaluated.",
            riskGroups: ["general", "pregnancy", "postpartum"],
            conditionTags: [],
            complicationTags: [],
            topicTags: ["symptoms", "urgent_symptoms", "care_team"],
            stage: ["pregnancy", "postpartum"],
            priority: 2
        ),
        PersonalizedLine(
            id: "postpartum-bleeding",
            title: "Postpartum Bleeding",
            contentType: "health",
            line: "Ask what amount of bleeding is expected after delivery and what amount is too much. Heavy bleeding, dizziness, or feeling faint should be treated seriously.",
            riskGroups: ["postpartum", "general"],
            conditionTags: [],
            complicationTags: ["bleeding_risk"],
            topicTags: ["postpartum", "symptoms", "urgent_symptoms"],
            stage: ["postpartum"],
            priority: 1
        ),
        PersonalizedLine(
            id: "advocate-what-should-be",
            title: "What Should Be",
            contentType: "advocacy",
            line: "Advocacy is not being difficult; it is helping your care match your real needs. Your questions can move care from “what is” toward “what should be.”",
            riskGroups: ["general"],
            conditionTags: [],
            complicationTags: [],
            topicTags: ["advocacy", "support"],
            stage: ["pregnancy", "postpartum", "lifetime"],
            priority: 4
        ),
        PersonalizedLine(
            id: "advocate-repeat-yourself",
            title: "Repeat Yourself",
            contentType: "advocacy",
            line: "If your concern was not understood the first time, repeat it in a clearer way or ask for it to be documented. Your safety is worth the extra sentence.",
            riskGroups: ["general", "higher_support_needs"],
            conditionTags: [],
            complicationTags: [],
            topicTags: ["advocacy", "care_team", "symptoms"],
            stage: ["pregnancy", "postpartum"],
            priority: 3
        ),
        PersonalizedLine(
            id: "advocate-ask-why",
            title: "Ask Why",
            contentType: "advocacy",
            line: "If a recommendation is confusing, ask why it matters and what the alternatives are. Understanding the plan can help you follow it and notice when something changes.",
            riskGroups: ["general"],
            conditionTags: [],
            complicationTags: [],
            topicTags: ["advocacy", "care_team", "support"],
            stage: ["pregnancy", "postpartum"],
            priority: 5
        ),
        PersonalizedLine(
            id: "advocate-bring-history",
            title: "Bring Your History",
            contentType: "advocacy",
            line: "Your past pregnancy complications, surgeries, medicines, and diagnoses are relevant even if the visit is short. Bringing them up helps your care team see the full picture.",
            riskGroups: ["preexisting_condition", "general"],
            conditionTags: [],
            complicationTags: ["preeclampsia", "gestational_diabetes", "gestational_hypertension"],
            topicTags: ["advocacy", "care_team", "screening"],
            stage: ["pregnancy", "postpartum", "lifetime"],
            priority: 4
        )
    ]
}
